; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

; ---- Shared settings -------------------------------------------------------
[common]
lib_extra_dirs = lib/core

; ---- ESP32 production target -----------------------------------------------
[env:esp32dev]
platform        = espressif32
board           = esp32dev
framework       = arduino
monitor_speed   = 115200
lib_extra_dirs  = ${common.lib_extra_dirs}

; ---- Native host target for unit tests -------------------------------------
[env:native]
platform        = native
test_framework  = unity
lib_extra_dirs  = ${common.lib_extra_dirs}
